### ISSUE TITLE
Does not return identical unicode string

### ISSUE THREAD

**Issue by johann-petrak** [coleifer/vedis-python#19]
```
db1 = Vedis(":mem:")
str_orig = "üöä"
db1["k1"] = str_orig
str_back = db1["k1"]
print("orig/type:", str_orig, type(str_orig), "back/type:", str_back, type(str_back), "same: ", str_orig == str_back)
```
Prints
```
orig/type: üöä <class 'str'> back/type: b'\xc3\xbc\xc3\xb6\xc3\xa4' <class 'bytes'> same:  False
```

I would expect a key-value store to return the same type as I put in

**Comment by coleifer** [comment]
This key/value store is wrapping a C library, which does not know anything about unicode. Vedis-python will encode your unicode strings as utf8 before storage, but when reading from the KV it cannot differentiate between a utf8-encoded unicode string or perhaps some arbitrary binary data like a JPG file or something. This is by design.

You can very easily wrap this with whatever kind of encoding/decoding you feel is appropriate.
